---
command: настройки
body: |
  Изменяет конфигурационные настройки

  Примеры использования
  настройки список                        - Список модифицируемых параметров
  настройки установить параметр значение  - Изменить значение параметра

  Допустимые настройки / Значения 
  autoloot    - (вкл / выкл)
  раткий      - (вкл / выкл)
  миникарта   - (вкл / выкл)

  Примеры
  настройка установить autoloot вкл  - Включает автоматический сбор лута
